---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_IP:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:

inputs:
  - name: concourse-vsphere
  - name: govc

run:
  path: concourse-vsphere/tasks/delete-opsman/task.sh
