---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  ICMP_CHECKS_ENABLED:
  INFRA_NETWORK_NAME:
  INFRA_SRVC_NW:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZS:
  DEPLOYMENT_NETWORK_NAME:
  DEPLOYMENT_SRVC_NW:
  DEPLOYMENT_VCENTER_NETWORK:
  DEPLOYMENT_NW_CIDR:
  DEPLOYMENT_EXCLUDED_RANGE:
  DEPLOYMENT_NW_DNS:
  DEPLOYMENT_NW_GATEWAY:
  DEPLOYMENT_NW_AZS:
  SERVICES_NETWORK_NAME:
  SERVICES_SRVC_NW:
  SERVICES_VCENTER_NETWORK:
  SERVICES_NW_CIDR:
  SERVICES_EXCLUDED_RANGE:
  SERVICES_NW_DNS:
  SERVICES_NW_GATEWAY:
  SERVICES_NW_AZS:
  DYNAMIC_SERVICES_NETWORK_NAME:
  DYNAMIC_SERVICES_SRVC_NW:
  DYNAMIC_SERVICES_VCENTER_NETWORK:
  DYNAMIC_SERVICES_NW_CIDR:
  DYNAMIC_SERVICES_EXCLUDED_RANGE:
  DYNAMIC_SERVICES_NW_DNS:
  DYNAMIC_SERVICES_NW_GATEWAY:
  DYNAMIC_SERVICES_NW_AZS:
  ISOLATION_SEGMENT_NETWORK_NAME:
  ISOLATION_SEGMENT_SRVC_NW:
  ISOLATION_SEGMENT_VSPHERE_NETWORK:
  ISOLATION_SEGMENT_NW_CIDR:
  ISOLATION_SEGMENT_EXCLUDED_RANGE:
  ISOLATION_SEGMENT_NW_DNS:
  ISOLATION_SEGMENT_NW_GATEWAY:
  ISOLATION_SEGMENT_NW_AZS:
  AZ_1:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CUSTER_NAME:
  AZ_3_RP_NAME:
  AZ_4:
  AZ_4_CUSTER_NAME:
  AZ_4_RP_NAME:
  AZ_5:
  AZ_5_CUSTER_NAME:
  AZ_5_RP_NAME:
  NTP_SERVERS:
  OPS_DIR_HOSTNAME:
  ENABLE_VM_RESURRECTOR:
  MAX_THREADS:
  TRUSTED_CERTIFICATES:
  GENERATE_VM_PASSWORDS:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-opsdir/task.sh
