resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: concourse-vsphere
  type: git
  source:
    uri: https://github.com/rahul-kj/concourse-vsphere
    branch: master

- name: customer-repo
  type: git
  source:
    uri: https://github.com/rahul-kj/sample-customer-repo
    branch: master

- name: pivnet-opsman-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager

- name: pivnet-er-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime

- name: pivnet-metrics-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-metrics

jobs:

- name: install-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: govc
      params:
        globs:
        - "*linux_amd64*"
    - get: om-cli
      globs: om-linux
    - get: pivnet-opsman-product
      params:
        globs:
        - "*.ova"
      trigger: true
    - get: jq
      params:
        globs:
        - "*linux64*"

  - task: deploy-opsman
    file: concourse-vsphere/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_data_center}}
      GOVC_DATASTORE: {{om_data_store}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      GOVC_HOST: {{om_vm_host}}
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      OPS_MGR_SSH_PWD: {{om_ssh_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_NETMASK: {{om_netmask}}
      OM_IP: {{om_ip}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_NAME: {{om_vm_name}}
      OM_RESOURCE_POOL: {{om_resource_pool}}
      OM_DISK_TYPE: {{om_disk_type}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}

  - task: config-opsman
    file: concourse-vsphere/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}

- name: configure-ops-director
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [install-opsmgr]
    - get: om-cli
      globs: om-linux
      passed: [install-opsmgr]
      trigger: true

  - task: config-opsdir
    file: concourse-vsphere/tasks/config-opsdir/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}
      VCENTER_DATA_CENTER: {{vcenter_data_center}}
      VCENTER_DISK_TYPE: {{vm_disk_type}}
      EPHEMERAL_STORAGE_NAMES: {{ephemeral_storage_names}}
      PERSISTENT_STORAGE_NAMES: {{persistent_storage_names}}
      ICMP_CHECKS_ENABLED: {{icmp_checks_enabled}}
      INFRA_NETWORK_NAME: {{infra_network_name}}
      INFRA_VCENTER_NETWORK: {{infra_vsphere_network}}
      INFRA_NW_CIDR: {{infra_nw_cidr}}
      INFRA_EXCLUDED_RANGE: {{infra_excluded_range}}
      INFRA_NW_DNS: {{infra_nw_dns}}
      INFRA_NW_GATEWAY: {{infra_nw_gateway}}
      INFRA_NW_AZS: {{infra_nw_azs}}
      DEPLOYMENT_NETWORK_NAME: {{deployment_network_name}}
      DEPLOYMENT_VCENTER_NETWORK: {{deployment_vsphere_network}}
      DEPLOYMENT_NW_CIDR: {{deployment_nw_cidr}}
      DEPLOYMENT_EXCLUDED_RANGE: {{deployment_excluded_range}}
      DEPLOYMENT_NW_DNS: {{deployment_nw_dns}}
      DEPLOYMENT_NW_GATEWAY: {{deployment_nw_gateway}}
      DEPLOYMENT_NW_AZS: {{deployment_nw_azs}}
      SERVICES_NETWORK_NAME: {{services_network_name}}
      SERVICES_VCENTER_NETWORK: {{services_vsphere_network}}
      SERVICES_NW_CIDR: {{services_nw_cidr}}
      SERVICES_EXCLUDED_RANGE: {{services_excluded_range}}
      SERVICES_NW_DNS: {{services_nw_dns}}
      SERVICES_NW_GATEWAY: {{services_nw_gateway}}
      SERVICES_NW_AZS: {{services_nw_azs}}
      DYNAMIC_SERVICES_NETWORK_NAME: {{dynamic_services_network_name}}
      DYNAMIC_SERVICES_VCENTER_NETWORK: {{dynamic_services_vsphere_network}}
      DYNAMIC_SERVICES_NW_CIDR: {{dynamic_services_nw_cidr}}
      DYNAMIC_SERVICES_EXCLUDED_RANGE: {{dynamic_services_excluded_range}}
      DYNAMIC_SERVICES_NW_DNS: {{dynamic_services_nw_dns}}
      DYNAMIC_SERVICES_NW_GATEWAY: {{dynamic_services_nw_gateway}}
      DYNAMIC_SERVICES_NW_AZS: {{dynamic_services_nw_azs}}
      AZ_1: {{az_1_name}}
      AZ_1_CUSTER_NAME: {{az_1_cluster_name}}
      AZ_1_RP_NAME: {{az_1_rp_name}}
      AZ_2: {{az_2_name}}
      AZ_2_CUSTER_NAME: {{az_2_cluster_name}}
      AZ_2_RP_NAME: {{az_2_rp_name}}
      AZ_3: {{az_3_name}}
      AZ_3_CUSTER_NAME: {{az_3_cluster_name}}
      AZ_3_RP_NAME: {{az_3_rp_name}}
      NTP_SERVERS: {{ntp_servers}}
      OPS_DIR_HOSTNAME: {{ops_dir_hostname}}
      ENABLE_VM_RESURRECTOR: {{enable_vm_resurrector}}
      MAX_THREADS: {{max_threads}}
      TRUSTED_CERTIFICATES: {{trusted_certificates}}
      GENERATE_VM_PASSWORDS: {{generate_vm_passwords}}

- name: opsman-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [configure-ops-director]
    - get: om-cli
      globs: om-linux
      passed: [configure-ops-director]
      trigger: true

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

- name: upload-elastic-runtime-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [opsman-apply-changes]
    - get: pivnet-product
      resource: pivnet-er-product
      params:
        globs:
        - "*.pivotal"
    - get: om-cli
      globs: om-linux
      passed: [opsman-apply-changes]
      trigger: true
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-er-tile
    file: concourse-vsphere/tasks/upload-product/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: {{company_proxy_domain}}
      OM_IP: {{om_ip}}

- name: config-elastic-runtime-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [upload-elastic-runtime-tile]
    - get: om-cli
      globs: om-linux
      passed: [upload-elastic-runtime-tile]
      trigger: true

  - task: config-er-tile
    file: concourse-vsphere/tasks/config-ert/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      ERT_SINGLETON_JOB_AZ: {{ert_singleton_job_az}}
      DEPLOYMENT_NW_AZS: {{deployment_nw_azs}}
      NETWORK_NAME: {{deployment_network_name}}
      ENABLE_SECURITY_EVENT_LOGGING: {{enable_security_event_logging}}
      SYSLOG_HOST: {{syslog_host}}
      SYSLOG_PORT: {{syslog_port}}
      SYSLOG_PROTOCOL: {{syslog_protocol}}
      SYSLOG_DRAIN_BUFFER_SIZE: {{syslog_drain_buffer_size}}
      COMPANY_NAME: {{company_name}}
      AUTHENTICATION_MODE: {{authentication_mode}}
      LOGGREGATOR_ENDPOINT_PORT: {{loggregator_endpoint_port}}
      SSL_TERMINATION: {{ssl_termination_point}}
      SSL_CERT: {{ssl_cert}}
      SSL_PRIVATE_KEY: {{ssl_private_key}}
      OPS_MGR_GENERATE_SSL_ENDPOINT: {{om_generate_ssl_endpoint}}
      DISABLE_HTTP_PROXY: {{disable_http_proxy}}
      TCP_ROUTING: {{tcp_routing}}
      TCP_ROUTING_PORTS: {{tcp_routing_ports}}
      ROUTE_SERVICES: {{route_services}}
      IGNORE_SSL_CERT: {{ignore_ssl_cert_verification}}
      SMTP_FROM: {{smtp_from}}
      SMTP_ADDRESS: {{smtp_address}}
      SMTP_PORT: {{smtp_port}}
      SMTP_USER: {{smtp_user}}
      SMTP_PWD: {{smtp_pwd}}
      SMTP_AUTH_MECHANISM: {{smtp_auth_mechanism}}
      LDAP_URL: {{ldap_url}}
      LDAP_USER: {{ldap_user}}
      LDAP_PWD: {{ldap_pwd}}
      SEARCH_BASE: {{search_base}}
      SEARCH_FILTER: {{search_filter}}
      GROUP_SEARCH_BASE: {{group_search_base}}
      GROUP_SEARCH_FILTER: {{group_search_filter}}
      MAIL_ATTR_NAME: {{mail_attribute_name}}
      FIRST_NAME_ATTR: {{first_name_attribute}}
      LAST_NAME_ATTR: {{last_name_attribute}}
      SECURITY_ACKNOWLEDGEMENT: {{security_acknowledgement}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB: {{default_quota_memory_limit_mb}}
      DEFAULT_QUOTA_MAX_SERVICES_COUNT: {{default_quota_max_number_services}}
      HA_PROXY_IPS: {{ha_proxy_ips}}
      SKIP_CERT_VERIFY: {{skip_cert_verify}}
      DISABLE_INSECURE_COOKIES: {{disable_insecure_cookies}}
      ROUTER_STATIC_IPS: {{router_static_ips}}
      ROUTER_REQUEST_TIMEOUT_IN_SEC: {{router_request_timeout_in_seconds}}
      GARDEN_NETWORK_POOL_CIDR: {{garden_network_pool_cidr}}
      GARDEN_NETWORK_MTU: {{garden_network_mtu}}
      MYSQL_MONITOR_EMAIL: {{mysql_monitor_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      ALLOW_APP_SSH_ACCESS: {{allow_app_ssh_access}}
      TCP_ROUTER_STATIC_IPS: {{tcp_router_static_ips}}
      SSH_STATIC_IPS: {{ssh_static_ips}}
      CONSUL_SERVER_INSTANCES: {{consul_server_instances}}
      NATS_INSTANCES: {{nats_instances}}
      ETCD_TLS_SERVER_INSTANCES: {{etcd_tls_server_instances}}
      NFS_SERVER_INSTANCES: {{nfs_server_instances}}
      MYSQL_PROXY_INSTANCES: {{mysql_proxy_instances}}
      MYSQL_INSTANCES: {{mysql_instances}}
      BACKUP_PREPARE_INSTANCES: {{backup_prepare_instances}}
      CCDB_INSTANCES: {{ccdb_instances}}
      UAADB_INSTANCES: {{uaadb_instances}}
      UAA_INSTANCES: {{uaa_instances}}
      CLOUD_CONTROLLER_INSTANCES: {{cloud_controller_instances}}
      HA_PROXY_INSTANCES: {{ha_proxy_instances}}
      ROUTER_INSTANCES: {{router_instances}}
      MYSQL_MONITOR_INSTANCES: {{mysql_monitor_instances}}
      CLOCK_GLOBAL_INSTANCES: {{clock_global_instances}}
      CLOUD_CONTROLLER_WORKER_INSTANCES: {{cloud_controller_worker_instances}}
      DIEGO_DATABASE_INSTANCES: {{diego_database_instances}}
      DIEGO_BRAIN_INSTANCES: {{diego_brain_instances}}
      DIEGO_CELL_INSTANCES: {{diego_cell_instances}}
      DOPPLER_INSTANCES: {{doppler_instances}}
      LOGGREGATOR_TC_INSTANCES: {{loggregator_traffic_controller_instances}}
      TCP_ROUTER_INSTANCES: {{tcp_router_instances}}

- name: upload-metrics-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [opsman-apply-changes]
    - get: pivnet-product
      resource: pivnet-metrics-product
      params:
        globs:
        - "*.pivotal"
    - get: om-cli
      globs: om-linux
      passed: [opsman-apply-changes]
      trigger: true
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-metrics-tile
    file: concourse-vsphere/tasks/upload-product/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: {{company_proxy_domain}}
      OM_IP: {{om_ip}}

- name: config-metrics-tile
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [upload-metrics-tile]
    - get: om-cli
      globs: om-linux
      passed: [upload-metrics-tile]
      trigger: true

  - task: config-metrics-tile
    file: concourse-vsphere/tasks/config-ops-metrics/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
      AZ_1: {{az_1_name}}
      NETWORK_NAME: {{infra_network_name}}
      JMX_ADMIN_USR: {{jmx_admin_usr}}
      JMX_ADMIN_PWD: {{jmx_admin_pwd}}
      JMX_SECURITY_LOGGING: {{jmx_security_logging}}
      JMX_USE_SSL: {{jmx_use_ssl}}

- name: pre-install-step
  plan:
  - aggregate:
    - get: customer-repo
    - get: om-cli
      globs: om-linux
      passed: [config-elastic-runtime-tile, config-metrics-tile]
      trigger: true

  - task: pre-step
    file: customer-repo/tasks/pre-step/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

- name: product-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [upload-metrics-tile]
    - get: om-cli
      globs: om-linux
      passed: [pre-install-step]
      trigger: true

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

# - name: disable-errands
#   plan:
#   - aggregate:
#     - get: concourse-vsphere
#       trigger: true
#       passed: [product-apply-changes]
#     - get: om-cli
#       globs: om-linux
#       passed: [product-apply-changes]
#
#   - task: disable-ert-errands
#     file: concourse-vsphere/tasks/disable-ert-errands/task.yml
#     params:
#       OPS_MGR_HOST: {{om_fqdn}}
#       OPS_MGR_USR: {{om_usr}}
#       OPS_MGR_PWD: {{om_pwd}}
#
#   - task: disable-metrics-errands
#     file: concourse-vsphere/tasks/disable-metrics-errands/task.yml
#     params:
#       OPS_MGR_HOST: {{om_fqdn}}
#       OPS_MGR_USR: {{om_usr}}
#       OPS_MGR_PWD: {{om_pwd}}

- name: update-metrics-ip-in-bosh
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [product-apply-changes]
    - get: om-cli
      globs: om-linux
      passed: [product-apply-changes]
      trigger: true

  - task: update-metrics-ip
    file: concourse-vsphere/tasks/update-metrics-ip/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

- name: post-install-step
  plan:
  - aggregate:
    - get: customer-repo
      passed: [pre-install-step]
    - get: om-cli
      globs: om-linux
      passed: [product-apply-changes]
      trigger: true
  - task: post-step
    file: customer-repo/tasks/post-step/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

- name: post-apply-changes
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [update-metrics-ip-in-bosh]
    - get: om-cli
      globs: om-linux
      passed: [update-metrics-ip-in-bosh, post-install-step]
      trigger: true

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}
