---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PRODUCT_IDENTIFIER:

inputs:
  - name: concourse-vsphere
  - name: om-cli
  - name: pivnet-product

run:
  path: concourse-vsphere/tasks/stage-product/task.sh
