---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  ERT_SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  NETWORK_NAME:
  ENABLE_SECURITY_EVENT_LOGGING:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_DRAIN_BUFFER_SIZE:
  COMPANY_NAME:
  AUTHENTICATION_MODE:
  LOGGREGATOR_ENDPOINT_PORT:
  SSL_TERMINATION:
  SSL_CERT:
  SSL_PRIVATE_KEY:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  TCP_ROUTING:
  TCP_ROUTING_PORTS:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT:
  SECURITY_ACKNOWLEDGEMENT:
  SMTP_FROM:
  SMTP_ADDRESS:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PWD:
  SMTP_AUTH_MECHANISM:
  LDAP_URL:
  LDAP_USER:
  LDAP_PWD:
  SEARCH_BASE:
  SEARCH_FILTER:
  GROUP_SEARCH_BASE:
  GROUP_SEARCH_FILTER:
  MAIL_ATTR_NAME:
  FIRST_NAME_ATTR:
  LAST_NAME_ATTR:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB:
  DEFAULT_QUOTA_MAX_SERVICES_COUNT:
  HA_PROXY_IPS:
  SKIP_CERT_VERIFY:
  DISABLE_INSECURE_COOKIES:
  ROUTER_STATIC_IPS:
  ROUTER_REQUEST_TIMEOUT_IN_SEC:
  GARDEN_NETWORK_POOL_CIDR:
  GARDEN_NETWORK_MTU:
  MYSQL_MONITOR_EMAIL:
  MYSQL_BACKUPS:
  ALLOW_APP_SSH_ACCESS:
  TCP_ROUTER_STATIC_IPS:
  SSH_STATIC_IPS:
  CONSUL_SERVER_INSTANCES:
  NATS_INSTANCES:
  ETCD_TLS_SERVER_INSTANCES:
  NFS_SERVER_INSTANCES:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCES:
  BACKUP_PREPARE_INSTANCES:
  CCDB_INSTANCES:
  UAADB_INSTANCES:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCES:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCES:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-ert/task.sh
