resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{github_token}} ## Optional: Removing this will call you to hit the rate limit

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}} ## Optional: Removing this will call you to hit the rate limit

- name: concourse-vsphere
  type: git
  source:
    uri: https://github.com/rahul-kj/concourse-vsphere
    branch: master

jobs:

- name: delete-installation
  plan:
  - aggregate:
    - get: concourse-vsphere
    - get: govc
      params:
        globs:
        - "*linux_amd64*"
    - get: om-cli
      globs: om-linux

  - task: delete-products
    file: concourse-vsphere/tasks/delete-products/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

  - task: apply-changes
    file: concourse-vsphere/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{om_fqdn}}
      OPS_MGR_USR: {{om_usr}}
      OPS_MGR_PWD: {{om_pwd}}

- name: delete-opsmgr
  plan:
  - aggregate:
    - get: concourse-vsphere
      passed: [delete-installation]
    - get: govc
      passed: [delete-installation]
      params:
        globs:
        - "*linux_amd64*"
    - get: om-cli
      passed: [delete-installation]
      globs: om-linux

  - task: delete-opsman
    file: concourse-vsphere/tasks/delete-opsman/task.yml
    params:
      OPS_MGR_IP: {{om_ip}}
      GOVC_INSECURE: 1
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
